version: '3'

services:
  dev:
    container_name: tasker
    build:
      context: . 
      dockerfile: dockers/dev/Dockerfile 
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 manage.py runserver 0.0.0.0:8080"
    volumes:
        - ./tasker/:/home
    ports:
        - 8081:8080  # All usage
        - 5000:5000  # A extra port
